"""initial schema

Revision ID: 78ad87157e85
Revises: 
Create Date: 2026-09-09 14:35:07.926065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78ad87157e85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ai_messages_conversation'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('idx_ai_conversations_user'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('idx_comments_author'), table_name='comments')
    op.drop_index(op.f('idx_comments_post'), table_name='comments')
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.drop_constraint(op.f('fk_comments_author'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_education_profiles_member'), table_name='education_profiles')
    op.create_index(op.f('ix_education_profiles_member_id'), 'education_profiles', ['member_id'], unique=False)
    op.alter_column('employment_profiles', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_employment_profiles_member'), table_name='employment_profiles')
    op.create_index(op.f('ix_employment_profiles_member_id'), 'employment_profiles', ['member_id'], unique=False)
    op.alter_column('event_rsvps', 'response',
               existing_type=postgresql.ENUM('YES', 'NO', 'MAYBE', 'DEFERRED', name='rsvp_response'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('event_rsvps', 'responded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_event_rsvps_event'), table_name='event_rsvps')
    op.drop_index(op.f('idx_event_rsvps_member'), table_name='event_rsvps')
    op.drop_constraint(op.f('uq_event_rsvp_unique'), 'event_rsvps', type_='unique')
    op.create_index(op.f('ix_event_rsvps_event_id'), 'event_rsvps', ['event_id'], unique=False)
    op.drop_constraint(op.f('chk_rsvp_has_identifier'), 'event_rsvps', type_='check')
    op.create_check_constraint('chk_rsvp_has_member_or_guest', 'event_rsvps', 'member_id IS NOT NULL OR guest_email IS NOT NULL')
    op.create_check_constraint('chk_rsvp_only_one_identifier', 'event_rsvps', 'NOT (member_id IS NOT NULL AND guest_email IS NOT NULL)')
    op.drop_column('event_rsvps', 'created_at')
    op.drop_column('event_rsvps', 'updated_at')
    op.alter_column('events', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('events', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('events', 'type',
               existing_type=postgresql.ENUM('BIRTHDAY', 'ANNIVERSARY', 'MEETING', 'OTHER', name='event_type'),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('events', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', 'CANCELLED', name='event_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::event_status"))
    op.drop_index(op.f('idx_events_family'), table_name='events')
    op.drop_index(op.f('idx_events_start_time'), table_name='events')
    op.drop_index(op.f('idx_events_type'), table_name='events')
    op.create_index(op.f('ix_events_family_id'), 'events', ['family_id'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.drop_constraint(op.f('chk_event_time_order'), 'events', type_='check')
    op.create_check_constraint('chk_event_end_after_start', 'events', 'end_time IS NULL OR end_time > start_time')
    op.alter_column('families', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'ARCHIVED', 'DELETED', name='family_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::family_status"))
    op.drop_index(op.f('idx_families_created_by'), table_name='families')
    op.drop_index(op.f('idx_family_branches_family'), table_name='family_branches')
    op.drop_index(op.f('idx_family_branches_founders'), table_name='family_branches')
    op.create_index(op.f('ix_family_branches_family_id'), 'family_branches', ['family_id'], unique=False)
    op.alter_column('family_members', 'date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('family_members', 'date_of_death',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('family_members', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DELETED', name='user_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::user_status"))
    op.drop_index(op.f('idx_family_members_branch'), table_name='family_members')
    op.drop_index(op.f('idx_family_members_family'), table_name='family_members')
    op.create_index(op.f('ix_family_members_family_id'), 'family_members', ['family_id'], unique=False)
    op.create_foreign_key(None, 'family_members', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('heritage_items', 'type',
               existing_type=postgresql.ENUM('DOCUMENT', 'IMAGE', 'MAP', 'ARTIFACT', 'STORY', name='heritage_type'),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('heritage_items', 'category',
               existing_type=postgresql.ENUM('DOCUMENT', 'STORY', 'OUTSTANDING', 'TRADITION', 'OTHER', name='heritage_category'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('heritage_items', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='heritage_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::heritage_status"))
    op.drop_index(op.f('idx_heritage_items_branch'), table_name='heritage_items')
    op.drop_index(op.f('idx_heritage_items_family'), table_name='heritage_items')
    op.create_index(op.f('ix_heritage_items_family_id'), 'heritage_items', ['family_id'], unique=False)
    op.alter_column('media_assets', 'media_type',
               existing_type=postgresql.ENUM('PHOTO', 'VIDEO', 'DOCUMENT', 'AUDIO', name='media_type'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('idx_media_assets_event'), table_name='media_assets')
    op.drop_index(op.f('idx_media_assets_family'), table_name='media_assets')
    op.drop_index(op.f('idx_media_assets_uploaded_by'), table_name='media_assets')
    op.create_index(op.f('ix_media_assets_event_id'), 'media_assets', ['event_id'], unique=False)
    op.create_index(op.f('ix_media_assets_family_id'), 'media_assets', ['family_id'], unique=False)
    op.create_index(op.f('ix_media_assets_uploaded_by'), 'media_assets', ['uploaded_by'], unique=False)
    op.drop_constraint(op.f('chk_media_at_least_one_parent'), 'media_assets', type_='check')
    op.alter_column('post_reactions', 'reaction_type',
               existing_type=postgresql.ENUM('LIKE', 'LOVE', 'CARE', 'HAPPY', 'SAD', 'ANGRY', 'WOW', name='reaction_type'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('idx_post_reactions_post'), table_name='post_reactions')
    op.drop_index(op.f('idx_post_reactions_user'), table_name='post_reactions')
    op.drop_constraint(op.f('uq_post_reaction_unique'), 'post_reactions', type_='unique')
    op.create_index(op.f('ix_post_reactions_post_id'), 'post_reactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_reactions_user_id'), 'post_reactions', ['user_id'], unique=False)
    op.create_unique_constraint('uq_post_reaction', 'post_reactions', ['post_id', 'user_id', 'reaction_type'])
    op.alter_column('posts', 'visibility_scope',
               existing_type=postgresql.ENUM('FAMILY', 'BRANCH', 'PUBLIC', name='post_visibility'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'FAMILY'::post_visibility"))
    op.alter_column('posts', 'status',
               existing_type=postgresql.ENUM('PUBLISHED', 'DRAFT', 'ARCHIVED', name='post_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PUBLISHED'::post_status"))
    op.drop_index(op.f('idx_posts_author'), table_name='posts')
    op.drop_index(op.f('idx_posts_family'), table_name='posts')
    op.drop_index(op.f('idx_posts_visibility'), table_name='posts')
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_family_id'), 'posts', ['family_id'], unique=False)
    op.drop_constraint(op.f('fk_posts_author'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.execute('DROP VIEW IF EXISTS family_tree_summary')
    op.alter_column('relationships', 'type',
               existing_type=postgresql.ENUM('PARENT_CHILD', 'MARRIAGE', 'SIBLING', 'OTHER', name='relationship_type'),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.execute("""CREATE OR REPLACE VIEW family_tree_summary AS
SELECT
    f.id AS family_id,
    f.family_name,
    fm.user_id,
    fm.full_name AS member_name,
    fm.gender,
    fm.is_alive,
    r.type AS relationship_type,
    r.from_member_id,
    r.to_member_id
FROM families f
LEFT JOIN family_members fm ON f.id = fm.family_id
LEFT JOIN relationships r ON (r.from_member_id = fm.id OR r.to_member_id = fm.id)
WHERE fm.user_id IS NOT NULL""")
    op.alter_column('relationships', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_relationships_from_member'), table_name='relationships')
    op.drop_index(op.f('idx_relationships_to_member'), table_name='relationships')
    op.drop_constraint(op.f('uq_relationship_unique'), 'relationships', type_='unique')
    op.create_index(op.f('ix_relationships_from_member_id'), 'relationships', ['from_member_id'], unique=False)
    op.create_index(op.f('ix_relationships_to_member_id'), 'relationships', ['to_member_id'], unique=False)
    op.drop_constraint(op.f('chk_relationship_different'), 'relationships', type_='check')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'SUPER_ADMIN', name='user_role'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::user_role"))
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DELETED', name='user_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::user_status"))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DELETED', name='user_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::user_status"))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('USER', 'ADMIN', 'SUPER_ADMIN', name='user_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::user_role"))
    op.create_check_constraint(op.f('chk_relationship_different'), 'relationships', 'from_member_id <> to_member_id')
    op.drop_index(op.f('ix_relationships_to_member_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_member_id'), table_name='relationships')
    op.create_unique_constraint(op.f('uq_relationship_unique'), 'relationships', ['from_member_id', 'to_member_id', 'type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_relationships_to_member'), 'relationships', ['to_member_id'], unique=False)
    op.create_index(op.f('idx_relationships_from_member'), 'relationships', ['from_member_id'], unique=False)
    op.alter_column('relationships', 'notes',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('relationships', 'type',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('PARENT_CHILD', 'MARRIAGE', 'SIBLING', 'OTHER', name='relationship_type'),
               existing_nullable=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_posts_author'), 'posts', 'users', ['author_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_posts_family_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.create_index(op.f('idx_posts_visibility'), 'posts', ['visibility_scope'], unique=False)
    op.create_index(op.f('idx_posts_family'), 'posts', ['family_id'], unique=False)
    op.create_index(op.f('idx_posts_author'), 'posts', ['author_id'], unique=False)
    op.alter_column('posts', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PUBLISHED', 'DRAFT', 'ARCHIVED', name='post_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'PUBLISHED'::post_status"))
    op.alter_column('posts', 'visibility_scope',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('FAMILY', 'BRANCH', 'PUBLIC', name='post_visibility'),
               existing_nullable=False,
               existing_server_default=sa.text("'FAMILY'::post_visibility"))
    op.drop_constraint('uq_post_reaction', 'post_reactions', type_='unique')
    op.drop_index(op.f('ix_post_reactions_user_id'), table_name='post_reactions')
    op.drop_index(op.f('ix_post_reactions_post_id'), table_name='post_reactions')
    op.create_unique_constraint(op.f('uq_post_reaction_unique'), 'post_reactions', ['post_id', 'user_id', 'reaction_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_post_reactions_user'), 'post_reactions', ['user_id'], unique=False)
    op.create_index(op.f('idx_post_reactions_post'), 'post_reactions', ['post_id'], unique=False)
    op.alter_column('post_reactions', 'reaction_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('LIKE', 'LOVE', 'CARE', 'HAPPY', 'SAD', 'ANGRY', 'WOW', name='reaction_type'),
               existing_nullable=False)
    op.create_check_constraint(op.f('chk_media_at_least_one_parent'), 'media_assets', 'event_id IS NOT NULL AND family_id IS NULL OR event_id IS NULL AND family_id IS NOT NULL')
    op.drop_index(op.f('ix_media_assets_uploaded_by'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_family_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_event_id'), table_name='media_assets')
    op.create_index(op.f('idx_media_assets_uploaded_by'), 'media_assets', ['uploaded_by'], unique=False)
    op.create_index(op.f('idx_media_assets_family'), 'media_assets', ['family_id'], unique=False)
    op.create_index(op.f('idx_media_assets_event'), 'media_assets', ['event_id'], unique=False)
    op.alter_column('media_assets', 'media_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PHOTO', 'VIDEO', 'DOCUMENT', 'AUDIO', name='media_type'),
               existing_nullable=False)
    op.drop_index(op.f('ix_heritage_items_family_id'), table_name='heritage_items')
    op.create_index(op.f('idx_heritage_items_family'), 'heritage_items', ['family_id'], unique=False)
    op.create_index(op.f('idx_heritage_items_branch'), 'heritage_items', ['branch_id'], unique=False)
    op.alter_column('heritage_items', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='heritage_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::heritage_status"))
    op.alter_column('heritage_items', 'category',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('DOCUMENT', 'STORY', 'OUTSTANDING', 'TRADITION', 'OTHER', name='heritage_category'),
               existing_nullable=False)
    op.alter_column('heritage_items', 'type',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('DOCUMENT', 'IMAGE', 'MAP', 'ARTIFACT', 'STORY', name='heritage_type'),
               existing_nullable=False)
    op.drop_constraint(None, 'family_members', type_='foreignkey')
    op.drop_index(op.f('ix_family_members_family_id'), table_name='family_members')
    op.create_index(op.f('idx_family_members_family'), 'family_members', ['family_id'], unique=False)
    op.create_index(op.f('idx_family_members_branch'), 'family_members', ['branch_id'], unique=False)
    op.alter_column('family_members', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'DELETED', name='user_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::user_status"))
    op.alter_column('family_members', 'date_of_death',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('family_members', 'date_of_birth',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_index(op.f('ix_family_branches_family_id'), table_name='family_branches')
    op.create_index(op.f('idx_family_branches_founders'), 'family_branches', ['founder_id'], unique=False)
    op.create_index(op.f('idx_family_branches_family'), 'family_branches', ['family_id'], unique=False)
    op.create_index(op.f('idx_families_created_by'), 'families', ['created_by'], unique=False)
    op.alter_column('families', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ACTIVE', 'ARCHIVED', 'DELETED', name='family_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::family_status"))
    op.drop_constraint('chk_event_end_after_start', 'events', type_='check')
    op.create_check_constraint(op.f('chk_event_time_order'), 'events', 'end_time IS NULL OR end_time > start_time')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_family_id'), table_name='events')
    op.create_index(op.f('idx_events_type'), 'events', ['type'], unique=False)
    op.create_index(op.f('idx_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('idx_events_family'), 'events', ['family_id'], unique=False)
    op.alter_column('events', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('OPEN', 'CLOSED', 'CANCELLED', name='event_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::event_status"))
    op.alter_column('events', 'type',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('BIRTHDAY', 'ANNIVERSARY', 'MEETING', 'OTHER', name='event_type'),
               existing_nullable=False)
    op.alter_column('events', 'end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('events', 'start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('event_rsvps', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('event_rsvps', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('chk_rsvp_only_one_identifier', 'event_rsvps', type_='check')
    op.drop_constraint('chk_rsvp_has_member_or_guest', 'event_rsvps', type_='check')
    op.create_check_constraint(op.f('chk_rsvp_has_identifier'), 'event_rsvps', 'member_id IS NOT NULL AND guest_email IS NULL OR member_id IS NULL AND guest_email IS NOT NULL')
    op.drop_index(op.f('ix_event_rsvps_event_id'), table_name='event_rsvps')
    op.create_unique_constraint(op.f('uq_event_rsvp_unique'), 'event_rsvps', ['event_id', 'member_id', 'guest_email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_event_rsvps_member'), 'event_rsvps', ['member_id'], unique=False)
    op.create_index(op.f('idx_event_rsvps_event'), 'event_rsvps', ['event_id'], unique=False)
    op.alter_column('event_rsvps', 'responded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('event_rsvps', 'response',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('YES', 'NO', 'MAYBE', 'DEFERRED', name='rsvp_response'),
               existing_nullable=False)
    op.drop_index(op.f('ix_employment_profiles_member_id'), table_name='employment_profiles')
    op.create_index(op.f('idx_employment_profiles_member'), 'employment_profiles', ['member_id'], unique=False)
    op.alter_column('employment_profiles', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_education_profiles_member_id'), table_name='education_profiles')
    op.create_index(op.f('idx_education_profiles_member'), 'education_profiles', ['member_id'], unique=False)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comments_author'), 'comments', 'users', ['author_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.create_index(op.f('idx_comments_post'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('idx_comments_author'), 'comments', ['author_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_messages_conversation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_messages_pkey'))
    )
    op.create_index(op.f('idx_ai_messages_conversation'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_conversations_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_conversations_pkey'))
    )
    op.create_index(op.f('idx_ai_conversations_user'), 'ai_conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###
